package ai.dnai.io.pseudorandomfilegenerator.api.exceptions

class WrongOrdersFromToRangeException(message: String) : GeneralCustomException(message) {
}